name: "FormatCheckComment"
on:
  workflow_dispatch:
permissions:
  pull-requests: "write"
  actions: "read"
jobs:
  format-check-comment:
    name: "FormatCheckComment"
    uses: "ITensor/ITensorActions/.github/workflows/FormatCheckComment.yml@v2"
    secrets: "inherit"
